### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by zDyant** [samu22cr/spicewal#1]
First. Sorry for opening a issue, i tried to get in touch with you in other ways but i failed.

Hey man I loved you project and I took a look at the files. If you have some time, I'd like to ask you: how did you manage to integrate with pywal? I've been staring at the code for several minutes and yet I can't figure it out.
Sry for my english. Thx

**Comment by samuelastua** [comment]
Hey...
No problem, but what do you mean? Are you asking about how to set up the theme  or how do I read pywal colors?
Glad you like it btw

**Comment by zDyant** [comment]
Thank you for help me out.
I was using a css of my own and I was facing some problems, I copy an file and edited it. Now it's working just fine!
